from dataclasses import dataclass
from datetime import datetime


@dataclass
class TelemetryRecord:
    """
    Structured telemetry observation generated by the ORBIT-X
    spacecraft digital twin.
    """

    timestamp: datetime

    spacecraft_id: str
    mission_id: str
    mode: str

    battery_level: float
    solar_generation: float
    power_load: float

    temperature: float
    thermal_state: str

    link_quality: float
    signal_strength: float
    packet_loss: float

    cpu_usage: float
    memory_usage: float
    flight_computer_status: str

    payload_status: str
    payload_activity_level: float

    position_x: float
    position_y: float
    position_z: float

    velocity: float

    attitude_pitch: float
    attitude_roll: float
    attitude_yaw: float